version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_vendas
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  produtos:
    build: ./produtos
    ports:
      - "5001:80"
    depends_on:
      - mysql

  clientes:
    build: ./clientes
    ports:
      - "5002:5002"
    depends_on:
      - mysql
  